### ISSUE TITLE
The download command doesn't seem to work

### ISSUE THREAD

**Issue by davidezanella** [adda25/pwm#1]
I tried to download a directory from a volume but the cli didn't do anything.

Moreover, from the help command, it seems that I can set as the download source only a volume, can I set a complete path of a file or a dir inside the volume?

**Comment by adda25** [comment]
You are right, the download command is not working right now. 
Yes, we want to allow to specify a dir or a file inside the volume.
This is issue will be solved in the next working day.

**Comment by adda25** [comment]
Now is possible to download the entire volume or a sub path with this command:

pwmcli download <VolumeName:/optionalSubPath/example> <AbsoluteLocalPathWhereToSave>

For instance, if your volume is named **home**, and inside this volume there is a folder named **myresults**,
the command for downloading the data is this one:

pwmcli download home:/myresults $(pwd)/saveddata
