### ISSUE TITLE
denied no match

### ISSUE THREAD

**Issue by paolorota** [adda25/pwm#3]
when a wk is on queue it gives a wrong message:

<img width="1522" alt="Screenshot 2020-11-10 at 17 11 14" src="https://user-images.githubusercontent.com/6144618/98701422-8daef300-2379-11eb-8a27-ed1ade7ae39d.png">

**Comment by adda25** [comment]
This is a wrong behaviour, we will fix in the next release.

**Comment by adda25** [comment]
Fixed
